name: Auto-Heal Detect

on:
  schedule:
    - cron: '10 0 * * *'
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Detect auto-heal candidates and write manifests
        id: detect
        run: |
          python scripts/auto_heal.py > detect_output.json
          cat detect_output.json

      - name: Ensure jq is available
        run: |
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y jq
          fi

      - name: Check for candidates
        id: check
        run: |
          COUNT=$(jq -r '.count // 0' detect_output.json || echo 0)
          if [ "$COUNT" = "0" ]; then
            echo "No candidates"
            echo "has_candidates=false" >> $GITHUB_OUTPUT
          else
            echo "Found $COUNT candidates"
            echo "has_candidates=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        id: create-pr
        if: steps.check.outputs.has_candidates == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          title: "Auto-Heal: Proposed Remediations"
          body: |
            This PR proposes auto-heal remediations based on policy and score history.
            - Generated by `scripts/auto_heal.py`
            - Please review manifests under `ops/autoheal/`
            - Merging will trigger enforcement via `autoheal_apply.yml`
          branch: autoheal-${{ github.run_number }}
          base: main
          labels: auto-heal
          reviewers: ${{ secrets.SECURITY_REVIEWERS }}
          commit-message: "autoheal: propose remediation for $(jq -r '.count // 0' detect_output.json) tokens"

      # Note: pending_action is only stored in manifest files (ops/autoheal/), not in token ledger
      # PR information is available in the PR itself and audit_trail entries in the ledger
